export const recommendationsProperty = [
    {
      id: 1,
      title: "대동 IC 근처 2000평 매물",
      description: "대동 IC 근처 차량 접근성 용이한 급매 매물",
      salesType: "매매",
      price: "4억 원",
      imageUrl: "/image/listings/room/0_0.webp",
    },
    {
      id: 2,
      title: "상동 매리 1200평 임대 매물",
      description: "차량 접근 용이, 주변 환경 좋은 매물",
      salesType: "임대",
      price: "4000/220 만 원",
      imageUrl: "/image/listings/room/0_1.webp",
    },
    {
      id: 3,
      title: "대동 IC 근처 2000평 매물",
      description: "대동 IC 근처 차량 접근성 용이한 급매 매물",
      salesType: "월세",
      price: "3400/100 만 원",
      imageUrl: "/image/listings/room/0_3.jpg",
    },
    {
      id: 4,
      title: "대동 IC 근처 700평 임대",
      description: "차량 접근 용이, 주변 환경 좋은 매물",
      salesType: "월세",
      price: "3400/200 만 원",
      imageUrl: "/image/listings/room/0_4.jpg",
    },
    {
      id: 5,
      title: "대동 IC 근처 800평 매물",
      description: "차량 접근 용이, 주변 환경 좋은 매물",
      salesType: "월세",
      price: "3400/200 만 원",
      imageUrl: "/image/listings/room/0_4.jpg",
    },
    {
      id: 6,
      title: "대동 IC 근처 300평 임대 매물",
      description: "차량 접근 용이, 주변 환경 좋은 매물",
      salesType: "임대",
      price: "3400/200 만 원",
      imageUrl: "/image/listings/room/0_5.jpg",
    },
    {
      id: 7,
      title: "상동 380평 임대 매물",
      description: "대동 IC 근처 차량 접근성 용이한 급매 매물",
      salesType: "임대",
      price: "3400/200 만 원",
      imageUrl: "/image/listings/room/0_6.jpg",
    },
    {
      id: 4,
      title: "대동 IC 근처 700평 임대",
      description: "차량 접근 용이, 주변 환경 좋은 매물",
      salesType: "월세",
      price: "3400/200 만 원",
      imageUrl: "/image/listings/room/0_4.jpg",
    },
    {
      id: 5,
      title: "대동 IC 근처 800평 매물",
      description: "차량 접근 용이, 주변 환경 좋은 매물",
      salesType: "월세",
      price: "3400/200 만 원",
      imageUrl: "/image/listings/room/0_4.jpg",
    },
    {
      id: 6,
      title: "대동 IC 근처 300평 임대 매물",
      description: "차량 접근 용이, 주변 환경 좋은 매물",
      salesType: "임대",
      price: "3400/200 만 원",
      imageUrl: "/image/listings/room/0_5.jpg",
    },
    {
      id: 7,
      title: "상동 380평 임대 매물",
      description: "대동 IC 근처 차량 접근성 용이한 급매 매물",
      salesType: "임대",
      price: "3400/200 만 원",
      imageUrl: "/image/listings/room/0_6.jpg",
    },
    {
      id: 4,
      title: "대동 IC 근처 700평 임대",
      description: "차량 접근 용이, 주변 환경 좋은 매물",
      salesType: "월세",
      price: "3400/200 만 원",
      imageUrl: "/image/listings/room/0_4.jpg",
    },
    {
      id: 5,
      title: "대동 IC 근처 800평 매물",
      description: "차량 접근 용이, 주변 환경 좋은 매물",
      salesType: "월세",
      price: "3400/200 만 원",
      imageUrl: "/image/listings/room/0_4.jpg",
    },
    {
      id: 6,
      title: "대동 IC 근처 300평 임대 매물",
      description: "차량 접근 용이, 주변 환경 좋은 매물",
      salesType: "임대",
      price: "3400/200 만 원",
      imageUrl: "/image/listings/room/0_5.jpg",
    },
    {
      id: 7,
      title: "상동 380평 임대 매물",
      description: "대동 IC 근처 차량 접근성 용이한 급매 매물",
      salesType: "임대",
      price: "3400/200 만 원",
      imageUrl: "/image/listings/room/0_6.jpg",
    },
    {
      id: 4,
      title: "대동 IC 근처 700평 임대",
      description: "차량 접근 용이, 주변 환경 좋은 매물",
      salesType: "월세",
      price: "3400/200 만 원",
      imageUrl: "/image/listings/room/0_4.jpg",
    },
    {
      id: 5,
      title: "대동 IC 근처 800평 매물",
      description: "차량 접근 용이, 주변 환경 좋은 매물",
      salesType: "월세",
      price: "3400/200 만 원",
      imageUrl: "/image/listings/room/0_4.jpg",
    },
    {
      id: 6,
      title: "대동 IC 근처 300평 임대 매물",
      description: "차량 접근 용이, 주변 환경 좋은 매물",
      salesType: "임대",
      price: "3400/200 만 원",
      imageUrl: "/image/listings/room/0_5.jpg",
    },
    {
      id: 7,
      title: "상동 380평 임대 매물",
      description: "대동 IC 근처 차량 접근성 용이한 급매 매물",
      salesType: "임대",
      price: "3400/200 만 원",
      imageUrl: "/image/listings/room/0_6.jpg",
    },
    {
      id: 4,
      title: "대동 IC 근처 700평 임대",
      description: "차량 접근 용이, 주변 환경 좋은 매물",
      salesType: "월세",
      price: "3400/200 만 원",
      imageUrl: "/image/listings/room/0_4.jpg",
    },
    {
      id: 5,
      title: "대동 IC 근처 800평 매물",
      description: "차량 접근 용이, 주변 환경 좋은 매물",
      salesType: "월세",
      price: "3400/200 만 원",
      imageUrl: "/image/listings/room/0_4.jpg",
    },
    {
      id: 6,
      title: "대동 IC 근처 300평 임대 매물",
      description: "차량 접근 용이, 주변 환경 좋은 매물",
      salesType: "임대",
      price: "3400/200 만 원",
      imageUrl: "/image/listings/room/0_5.jpg",
    },
    {
      id: 7,
      title: "상동 380평 임대 매물",
      description: "대동 IC 근처 차량 접근성 용이한 급매 매물",
      salesType: "임대",
      price: "3400/200 만 원",
      imageUrl: "/image/listings/room/0_6.jpg",
    },
  ]

  // Assign unique id values
export const recommendationsPropertyArray = recommendationsProperty.map((property, index) => ({
  ...property,
  id: index + 1,
}));